/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import control.controllerKoneksi;
import control.controllerToko;
import model.modelToko;
import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author arumia
 */
public class viewHome extends javax.swing.JFrame {
    
    controllerToko ctoko;
    List<modelToko>listdata = new ArrayList();
    /**
     * Creates new form viewHome
     */
    public viewHome() {
        initComponents();
        ctoko = new controllerToko(this);
        ctoko.isiTable();
    }
    
    public JTextField getTxtKode(){return jtextKodeBarang;}
    public JTextField getTxtNama() {return jtextNamaBarang;}
    public JComboBox getCbKategori() {return comboKategori;}
    public JComboBox getCbJenis() {return comboJenisPackaging;}
    public JTextField getTxtHarga() {return jtextHarga;}
    public JComboBox getCbCariKategori() {return comboCariKategori;}
    public JButton getButtonHapus() {return buttonHapus;}
    public JButton getButtonBersih() {return buttonBersihkan;}
    public JButton getButtonSimpan() {return buttonSimpan;}
    public JButton getButtonUbah() {return buttonUbah;}
    public JButton getButtonKeluar() {return buttonKeluar;}
    public JTable getTableData() {return Tabel1;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtextAdmin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtextHarga = new javax.swing.JTextField();
        jtextKodeBarang = new javax.swing.JTextField();
        jtextNamaBarang = new javax.swing.JTextField();
        comboKategori = new javax.swing.JComboBox<>();
        comboJenisPackaging = new javax.swing.JComboBox<>();
        buttonSimpan = new javax.swing.JButton();
        buttonBersihkan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        comboCariKategori = new javax.swing.JComboBox<>();
        buttonCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel1 = new javax.swing.JTable();
        buttonUbah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setText("Admin Toko :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 90, 30);

        jtextAdmin.setEditable(false);
        jtextAdmin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtextAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextAdminActionPerformed(evt);
            }
        });
        jPanel1.add(jtextAdmin);
        jtextAdmin.setBounds(100, 10, 140, 30);

        jLabel2.setFont(new java.awt.Font("Britannic Bold", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Data Barang");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 20, 840, 40);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 80, 820, 430);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 70);

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel3.setText("Harga");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 180, 90, 30);

        jLabel4.setText("Kode Barang");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 20, 90, 30);

        jLabel5.setText("Nama Barang");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 60, 90, 30);

        jLabel6.setText("Kategori Barang");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 100, 90, 30);

        jLabel7.setText("Jenis Packaging");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 140, 100, 30);
        jPanel2.add(jtextHarga);
        jtextHarga.setBounds(130, 180, 150, 30);
        jPanel2.add(jtextKodeBarang);
        jtextKodeBarang.setBounds(130, 20, 150, 30);
        jPanel2.add(jtextNamaBarang);
        jtextNamaBarang.setBounds(130, 60, 150, 30);

        comboKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Alat Mandi", "Alat Tulis", "Alat Rumah Tangga" }));
        comboKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboKategoriActionPerformed(evt);
            }
        });
        jPanel2.add(comboKategori);
        comboKategori.setBounds(130, 100, 150, 30);

        comboJenisPackaging.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Satuan", "Pack" }));
        jPanel2.add(comboJenisPackaging);
        comboJenisPackaging.setBounds(130, 140, 150, 30);

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSimpan);
        buttonSimpan.setBounds(70, 230, 80, 30);

        buttonBersihkan.setText("Bersihkan");
        buttonBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBersihkanActionPerformed(evt);
            }
        });
        jPanel2.add(buttonBersihkan);
        buttonBersihkan.setBounds(160, 230, 90, 30);

        jPanel6.add(jPanel2);
        jPanel2.setBounds(20, 20, 310, 280);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Pencarian Berdasarkan Kategori Makanan");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(0, 10, 310, 30);

        comboCariKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Alat Mandi", "Alat Tulis", "Alat Rumah Tangga", " " }));
        jPanel4.add(comboCariKategori);
        comboCariKategori.setBounds(40, 50, 160, 30);

        buttonCari.setText("Cari");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });
        jPanel4.add(buttonCari);
        buttonCari.setBounds(210, 50, 60, 30);

        jPanel6.add(jPanel4);
        jPanel4.setBounds(20, 310, 310, 100);

        Tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "kode_barang", "nama_barang", "kategori", "jenis", "harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel1);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(340, 100, 480, 310);

        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });
        jPanel6.add(buttonUbah);
        buttonUbah.setBounds(510, 50, 80, 30);

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });
        jPanel6.add(buttonHapus);
        buttonHapus.setBounds(600, 50, 80, 30);

        buttonKeluar.setText("Keluar");
        buttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKeluarActionPerformed(evt);
            }
        });
        jPanel6.add(buttonKeluar);
        buttonKeluar.setBounds(740, 50, 80, 30);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 70, 840, 430);

        setBounds(0, 0, 854, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void jtextAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextAdminActionPerformed
        
    }//GEN-LAST:event_jtextAdminActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        ctoko.SimpanData();
        ctoko.isiTable();
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        ctoko.Ubah();
        ctoko.isiTable();
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBersihkanActionPerformed
        ctoko.Reset();
    }//GEN-LAST:event_buttonBersihkanActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        ctoko.Hapus();
        ctoko.isiTable();
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_buttonKeluarActionPerformed

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        ctoko.cariKategori();
    }//GEN-LAST:event_buttonCariActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String user1 = viewLogin.user;
        jtextAdmin.setText(user1);
    }//GEN-LAST:event_formWindowOpened

    private void comboKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboKategoriActionPerformed

    private void Tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel1MouseClicked
    ctoko.isiField(Tabel1.getSelectedRow());        // TODO add your handling code here:
    }//GEN-LAST:event_Tabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel1;
    private javax.swing.JButton buttonBersihkan;
    private javax.swing.JButton buttonCari;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonKeluar;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JComboBox<String> comboCariKategori;
    private javax.swing.JComboBox<String> comboJenisPackaging;
    private javax.swing.JComboBox<String> comboKategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtextAdmin;
    private javax.swing.JTextField jtextHarga;
    private javax.swing.JTextField jtextKodeBarang;
    private javax.swing.JTextField jtextNamaBarang;
    // End of variables declaration//GEN-END:variables
}
